# Usar uma imagem base do OpenJDK
FROM openjdk:11-jre-slim

# Diretório de trabalho dentro do contêiner
WORKDIR /mondodb_springboot/

# Copiar o arquivo pom.xml e a pasta src para o diretório de trabalho
COPY pom.xml /mondodb_springboot
COPY src /mondodb_springboot/src

# Instalar as dependências do Maven e compilar a aplicação
RUN apt-get update && \
    apt-get install -y maven && \
    mvn clean install

# Expõe a porta que a aplicação vai rodar
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "target\springboot_mobgodb-0.0.1-SNAPSHOT.jar"]
