name: springboot-mongodb

services:
  # Serviço de aplicação Spring Boot
  app:
    type: web
    dockerfilePath: ./Dockerfile
    build: .
    env:
      SPRING_APPLICATION_NAME value: springboot-mongodb
      MONGO_HOST value: mongodb
      MONGO_PORT value: 27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  # Serviço MongoDB
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
